export type PaymentResult={accepted:boolean,reference?:string};export interface PaymentProvider{createPayment(input:{orderId:string,amountPaise:number}):Promise<PaymentResult>;verifyWebhook(raw:string,signature:string):boolean}
export interface NotificationProvider{send(input:{to:string,title:string,body:string}):Promise<void>}
export interface OcrProvider{extract(input:{objectKey:string}):Promise<{pages:Array<{pageNumber:number,text:string,wordCount:number}>}>}
export interface MalwareScanner{scan(input:{objectKey:string}):Promise<{clean:boolean,reason?:string}>}
export class NoopPaymentProvider implements PaymentProvider{async createPayment(){return{accepted:false}}verifyWebhook(){return false}}
export class ConsoleNotificationProvider implements NotificationProvider{async send(input:{to:string,title:string,body:string}){if(process.env.NODE_ENV==="development")console.log("[notification]",input)}}
export class HttpOcrProvider implements OcrProvider{async extract(input:{objectKey:string}){if(!process.env.OCR_ENDPOINT)throw new Error("OCR provider not configured");const r=await fetch(process.env.OCR_ENDPOINT+"/extract",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(input)});if(!r.ok)throw new Error("ocr_failed");return await r.json() as {pages:Array<{pageNumber:number,text:string,wordCount:number}>}}}
export class HttpMalwareScanner implements MalwareScanner{async scan(input:{objectKey:string}){if(!process.env.MALWARE_SCAN_ENDPOINT){if(process.env.NODE_ENV==="production")return{clean:false,reason:"scanner_not_configured"};return{clean:true}}const r=await fetch(process.env.MALWARE_SCAN_ENDPOINT+"/scan",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(input)});if(!r.ok)throw new Error("scan_failed");return await r.json() as {clean:boolean,reason?:string}}}
export async function createConfiguredPayment(input:{orderId:string,amountPaise:number}){if(process.env.NODE_ENV==="development"&&process.env.ALLOW_TEST_PAYMENTS==="true")return{accepted:true,reference:"test_"+input.orderId};throw new Error("payment_provider_not_configured")}
