import"dotenv/config";import crypto from"node:crypto";import express from"express";import cors from"cors";import helmet from"helmet";import rateLimit from"express-rate-limit";import{z}from"zod";import{auth,role}from"./middleware.js";import{hashToken,issueAccessToken,issueRefreshToken,otp,requestId}from"./security.js";import{pool,withTx}from"./db.js";import{canTransition,orderAmounts,publicOrderId}from"./domain.js";import{marketplace}from"./marketplace.js";
const app=express();app.disable("x-powered-by");app.set("trust proxy",1);app.use(helmet({crossOriginResourcePolicy:{policy:"same-site"}}));app.use(cors({origin:process.env.WEB_ORIGIN?.split(",").map(x=>x.trim())||false,credentials:true}));app.use(express.json({limit:"1mb",verify:(req:any,_res,buf)=>{req.rawBody=Buffer.from(buf)}}));app.use((req,res,next)=>{res.setHeader("x-request-id",requestId());next()});app.use(rateLimit({windowMs:60_000,max:120,standardHeaders:true,legacyHeaders:false}));app.use(marketplace);
const otpLimit=rateLimit({windowMs:10*60_000,max:5,standardHeaders:true,legacyHeaders:false});
function cookie(req:express.Request,name:string){const raw=req.header("cookie")||"";return raw.split(";").map(x=>x.trim()).find(x=>x.startsWith(name+"="))?.slice(name.length+1)}
function setRefresh(res:express.Response,value:string){res.setHeader("Set-Cookie",`refresh_token=${value}; Max-Age=2592000; Path=/auth; HttpOnly; ${process.env.NODE_ENV==="production"?" Secure":""}; SameSite=Lax`)}
app.get("/health",async(_,res)=>{try{await pool.query("SELECT 1");res.json({ok:true,service:"scribelink-api"})}catch{res.status(503).json({ok:false})}});
app.post("/auth/request-otp",otpLimit,async(req,res)=>{const parsed=z.object({phone:z.string().trim().regex(/^\\+[1-9]\\d{7,14}$/)}).safeParse(req.body);if(!parsed.success)return res.status(400).json({error:"invalid_request"});const phone=parsed.data.phone;const code=otp();await pool.query("INSERT INTO auth_challenges(phone_e164,otp_hash,expires_at) VALUES($1,$2,now()+interval '5 minutes')",[phone,hashToken(code)]);res.json({accepted:true,expiresIn:300,developmentOtp:process.env.NODE_ENV==="development"?code:undefined})});
app.post("/auth/verify-otp",async(req,res)=>{const parsed=z.object({phone:z.string().trim().regex(/^\\+[1-9]\\d{7,14}$/),code:z.string().regex(/^\\d{6}$/)}).safeParse(req.body);if(!parsed.success)return res.status(400).json({error:"invalid_request"});const{phone,code}=parsed.data;const result=await withTx(async c=>{const q=await c.query("SELECT id,otp_hash,expires_at,attempts FROM auth_challenges WHERE phone_e164=$1 AND consumed_at IS NULL ORDER BY created_at DESC LIMIT 1 FOR UPDATE",[phone]);const ch=q.rows[0];if(!ch||new Date(ch.expires_at)<new Date()||ch.attempts>=5||hashToken(code)!==ch.otp_hash)throw new Error("invalid_otp");await c.query("UPDATE auth_challenges SET consumed_at=now() WHERE id=$1",[ch.id]);const u=await c.query("INSERT INTO users(phone_e164) VALUES($1) ON CONFLICT(phone_e164) DO UPDATE SET updated_at=now() RETURNING id,role",[phone]);const refresh=issueRefreshToken();await c.query("INSERT INTO sessions(user_id,refresh_token_hash,expires_at) VALUES($1,$2,now()+interval '30 days')",[u.rows[0].id,hashToken(refresh)]);return{user:u.rows[0],refresh}}).catch(()=>null);if(!result)return res.status(401).json({error:"invalid_otp"});setRefresh(res,result.refresh);res.json({accessToken:issueAccessToken(result.user.id,result.user.role)})});
app.post("/auth/logout",async(req,res)=>{const raw=cookie(req,"refresh_token")||z.string().min(32).safeParse(req.body?.refreshToken).data;if(raw)await pool.query("UPDATE sessions SET revoked_at=now() WHERE refresh_token_hash=$1",[hashToken(raw)]);res.setHeader("Set-Cookie",`refresh_token=; Max-Age=0; Path=/auth; HttpOnly; ${process.env.NODE_ENV==="production"?"Secure; ":""}SameSite=Lax`);res.status(204).send()});
app.post("/auth/refresh",async(req,res)=>{const raw=cookie(req,"refresh_token")||z.string().min(32).safeParse(req.body?.refreshToken).data;if(!raw)return res.status(401).json({error:"invalid_refresh"});const result=await withTx(async c=>{const q=await c.query("SELECT s.id,s.user_id,u.role FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.refresh_token_hash=$1 AND s.revoked_at IS NULL AND s.expires_at>now() FOR UPDATE",[hashToken(raw)]);const row=q.rows[0];if(!row)throw new Error("invalid_refresh");const next=issueRefreshToken();await c.query("UPDATE sessions SET revoked_at=now() WHERE id=$1",[row.id]);await c.query("INSERT INTO sessions(user_id,refresh_token_hash,expires_at) VALUES($1,$2,now()+interval '30 days')",[row.user_id,hashToken(next)]);return{userId:row.user_id,role:row.role,next}}).catch(()=>null);if(!result)return res.status(401).json({error:"invalid_refresh"});setRefresh(res,result.next);res.json({accessToken:issueAccessToken(result.userId,result.role)})});
app.get("/me",auth,async(req,res)=>{const q=await pool.query("SELECT id,role,is_active,created_at FROM users WHERE id=$1",[(req as any).user.sub]);if(!q.rows[0]||!q.rows[0].is_active)return res.status(401).json({error:"inactive_account"});res.json({user:q.rows[0]})});
app.post("/orders",auth,async(req,res)=>{const body=z.object({pages:z.number().int().positive().max(500)}).safeParse(req.body);if(!body.success)return res.status(400).json({error:"invalid_request"});const amounts=orderAmounts(body.data.pages);const created=await withTx(async c=>{const id=publicOrderId();const q=await c.query("INSERT INTO orders(public_id,customer_id,pages,price_paise,payout_paise,status) VALUES($1,$2,$3,$4,$5,'DRAFT') RETURNING public_id,pages,price_paise,payout_paise,status",[id,(req as any).user.sub,body.data.pages,amounts.pricePaise,amounts.payoutPaise]);await c.query("INSERT INTO order_events(order_id,to_status,actor_user_id,metadata) SELECT id,status,$2,'{}' FROM orders WHERE public_id=$1",[id,(req as any).user.sub]);return q.rows[0]});res.status(201).json({id:created.public_id,pages:created.pages,price:created.price_paise/100,payout:created.payout_paise/100,status:created.status})});
app.get("/orders/:id",auth,async(req,res)=>{const q=await pool.query("SELECT public_id,pages,price_paise,payout_paise,status,created_at,updated_at FROM orders WHERE public_id=$1 AND customer_id=$2",[req.params.id,(req as any).user.sub]);if(!q.rows[0])return res.status(404).json({error:"not_found"});res.json({...q.rows[0],price:q.rows[0].price_paise/100})});
app.post("/orders/:id/transition",auth,async(req,res)=>{const body=z.object({to:z.enum(["CANCELLED"])}).safeParse(req.body);if(!body.success)return res.status(400).json({error:"invalid_request"});const result=await withTx(async c=>{const q=await c.query("SELECT id,status FROM orders WHERE public_id=$1 AND customer_id=$2 FOR UPDATE",[req.params.id,(req as any).user.sub]);const o=q.rows[0];if(!o)return null;if(!canTransition(o.status,body.data.to))throw new Error("invalid_transition");await c.query("UPDATE orders SET status=$1,version=version+1,updated_at=now() WHERE id=$2",[body.data.to,o.id]);await c.query("INSERT INTO order_events(order_id,from_status,to_status,actor_user_id) VALUES($1,$2,$3,$4)",[o.id,o.status,body.data.to,(req as any).user.sub]);return{status:body.data.to}}).catch(e=>e instanceof Error&&e.message==="invalid_transition"?"invalid_transition":null);if(result===null)return res.status(404).json({error:"not_found"});if(result==="invalid_transition")return res.status(409).json({error:"invalid_transition"});res.json(result)});
app.post("/admin/audit-test",auth,role("ADMIN"),(_,res)=>res.json({ok:true}));
const port=Number(process.env.PORT||4000);app.listen(port,()=>console.log(`ScribeLink API listening on ${port}`));